## **Le 17/11/2018 au matin**

## I) Importation des données "Fashion"

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

data_train_file = "data/fashion/fashion-mnist_train.csv"
data_test_file = "data/fashion/fashion-mnist_test.csv"

df_train = pd.read_csv(data_train_file)
df_test = pd.read_csv(data_test_file)

## II) Visualisation et exploration des données

In [2]:
df_train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_test.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Train_set : Select all columns without the 1st column
train_features = df_train[df_train.columns[1:]]
train_features.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,5,0,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,1,2,0,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Test_set : Select all columns without the 1st column
test_features = df_test[df_test.columns[1:]]
test_features.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,9,8,0,...,103,87,56,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,0,63,53,31,0,0,0
3,0,0,0,0,0,0,0,0,0,161,...,137,126,140,0,133,224,222,56,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
train_labels = df_train['label']
train_labels.describe()

count    60000.000000
mean         4.500000
std          2.872305
min          0.000000
25%          2.000000
50%          4.500000
75%          7.000000
max          9.000000
Name: label, dtype: float64

In [7]:
test_labels = df_test['label']
test_labels.describe()

count    10000.000000
mean         4.500000
std          2.872425
min          0.000000
25%          2.000000
50%          4.500000
75%          7.000000
max          9.000000
Name: label, dtype: float64

In [8]:
print("Train features shape :")
train_features.values.shape

Train features shape :

(60000, 784)

In [9]:
print("Train labels shape :")
train_labels.values.shape

Train labels shape :

(60000,)

In [10]:
print("Test features shape :")
test_features.values.shape

Test features shape :

(10000, 784)

In [11]:
print("Test labels shape :")
test_labels.values.shape

Test labels shape :

(10000,)

In [12]:
print(train_features.describe())
print(test_features.describe())

             pixel1        pixel2        pixel3        pixel4        pixel5  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000
mean       0.000900      0.006150      0.035333      0.101933      0.247967
std        0.094689      0.271011      1.222324      2.452871      4.306912
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max       16.000000     36.000000    226.000000    164.000000    227.000000

             pixel6        pixel7        pixel8        pixel9       pixel10  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000
mean       0.411467      0.805767      2.198283      5.682000     14.488767
std        5.836188      8.215169     14.093378     23.819481     38.334549
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max      230.000000    224.000000    255.000000    254.000000    255.000000

          ...           pixel775      pixel776      pixel777      pixel778  \
count     ...       60000.000000  60000.000000  60000.000000  60000.000000
mean      ...          34.625400     23.300683     16.588267     17.869433
std       ...          57.545242     48.854427     41.979611     43.966032
min       ...           0.000000      0.000000      0.000000      0.000000
25%       ...           0.000000      0.000000      0.000000      0.000000
50%       ...           0.000000      0.000000      0.000000      0.000000
75%       ...          58.000000      9.000000      0.000000      0.000000
max       ...         255.000000    255.000000    255.000000    255.000000

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000
mean      22.814817     17.911483      8.520633      2.753300      0.855517
std       51.830477     45.149388     29.614859     17.397652      9.356960
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max      255.000000    255.000000    255.000000    255.000000    255.000000

          pixel784
count  60000.00000
mean       0.07025
std        2.12587
min        0.00000
25%        0.00000
50%        0.00000
75%        0.00000
max      170.00000

[8 rows x 784 columns]
             pixel1        pixel2        pixel3        pixel4        pixel5  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean       0.000400      0.010300      0.052100      0.077000      0.208600
std        0.024493      0.525187      2.494315      2.208882      4.669183
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max        2.000000     45.000000    218.000000    185.000000    227.000000

             pixel6        pixel7        pixel8        pixel9       pixel10  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean       0.349200      0.826700      2.321200      5.457800     14.363500
std        5.657849      8.591731     15.031508     23.359019     37.911701
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max      223.000000    247.000000    218.000000    244.000000    250.000000

          ...           pixel775      pixel776      pixel777      pixel778  \
count     ...       10000.000000  10000.000000  10000.000000  10000.000000
mean      ...          34.320800     23.071900     16.432000     17.870600
std       ...          57.888679     49.049749     42.159665     44.140552
min       ...           0.000000      0.000000      0.000000      0.000000
25%       ...           0.000000      0.000000      0.000000      0.000000
50%       ...           0.000000      0.000000      0.000000      0.000000
75%       ...          55.000000      6.000000      0.000000      0.000000
max       ...         254.000000    252.000000    255.000000    255.000000

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean      22.860000     17.790200      8.353500      2.541600      0.629500
std       51.706601     45.128107     28.765769     16.417363      7.462533
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        1.000000      0.000000      0.000000      0.000000      0.000000
max      255.000000    255.000000    240.000000    225.000000    205.000000

          pixel784
count  10000.00000
mean       0.06560
std        1.93403
min        0.00000
25%        0.00000
50%        0.00000
75%        0.00000
max      107.00000

[8 rows x 784 columns]

In [13]:
X_train = train_features.values
X_test = test_features.values
y_train = train_labels.values
y_test = test_labels.values

## III) Preprocessing des données

In [14]:
from sklearn.preprocessing import StandardScaler
print('\nPreprocessing on Training and Validation Data...')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Preprocessing on Training and Validation Data...

C:\Users\aden\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

## IV) Prédiction via le SVM avec différents hyperparamètres

In [16]:
import itertools
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

class svm_model:
    
    def __init__(self, C_value=1, kernel_value='rbf'):
        self.C_value = C_value
        self.kernel_value = kernel_value
        self.classifier = SVC(C = self.C_value, kernel = self.kernel_value, random_state=0)
        print('\n====== SVM Classifier with C = ' + str(self.C_value) + ' kernel = ' + self.kernel_value + '=========')
        
    def svm_train(self, X_train, y_train):
        self.classifier.fit(X_train, y_train)
        
    def svm_predict(self, X_test):
        self.y_pred = self.classifier.predict(X_test)
        
    def svm_print_accuracy_score(self, y_test):
        print('\nCalculating Accuracy of Predictions...')
        self.y_test = y_test
        print("Accuracy score : ", accuracy_score(self.y_test, self.y_pred))

    def search_by_gridSearch_with_only_SVM(self, X_train, y_train, C_values, cv=10): 
        hyerparams = [{'C': C_values, 'kernel': ['linear']},
                      {'C': C_values, 'kernel': ['rbf']}]
        self.grid_search = GridSearchCV(SVC(),
                                      param_grid = hyerparams,
                                      scoring = 'accuracy',
                                      cv = cv,
                                      n_jobs = -1)
        self.grid_search.fit(X_train, y_train)
      
    def print_best_score_find_by_gridSearch(self):
        print("Meilleur résultat de la validation croisée :", self.grid_search.best_score_)
        print("Meilleur(s) hyperparamètre(s) sur le jeu d'entraînement:", self.grid_search.best_params_)
      
    def print_score_of_generalisation_on_test_set(self, X_test, y_test):
        # Après avoir trouvé la meilleure combinaison de paramètres, il est 
        # important de calculer l'erreur de généralisation sur le test_set
        self.grid_search_y_pred = grid_search.predict(X_test)
        print("\nResultat sur le jeu de test : %0.3f" % metrics.accuracy_score(y_test, self.grid_search_y_pred))

    def plot_confusion_matrix(self): 
        # Plot Confusion Matrix for Test Data
        normalize=False
        cm = confusion_matrix(self.y_test, self.y_pred)
        cmap=plt.cm.Blues
        classes = ['T-Shirt/Top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle Boot']
        
        plt.imshow(cm, interpolation='nearest', cmap=cmap)
        plt.title('Confusion Matrix for Test Data')
        plt.colorbar()
        tick_marks = np.arange(len(classes))
        plt.xticks(tick_marks, classes, rotation=45)
        plt.yticks(tick_marks, classes)
        
        fmt = '.2f' if normalize else 'd'
        thresh = cm.max() / 2.
        for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
            plt.text(j, i, format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")

        plt.ylabel('True label')
        plt.xlabel('Predicted label')
        plt.tight_layout()
        plt.grid('off')
        plt.show()

### Les meilleurs scores ont été obtenus par les modèles suivants : 
- SVM(C=10, Kernel =”rbf”)	 : test = 90.75%
- SVM(C=100, Kernel =”rbf”)	 : test = 90.46%.
- SVM(C=10, Kernel =”poly”)	 : test = 90.39%

In [ ]:
svm_C1_rbf = svm_model(C_value=1, kernel_value='rbf')
svm_C1_rbf.svm_train(X_train, y_train)
svm_C1_rbf.svm_predict(X_test)
svm_C1_rbf.svm_print_accuracy_score(y_test)

In [ ]:
svm_C1_poly = svm_model(C_value=1, kernel_value='poly')
svm_C1_poly.svm_train(X_train, y_train)
svm_C1_poly.svm_predict(X_test)
svm_C1_poly.svm_print_accuracy_score(y_test)

In [ ]:
svm_C1_linear = svm_model(C_value=1, kernel_value='linear')
svm_C1_linear.svm_train(X_train, y_train)
svm_C1_linear.svm_predict(X_test)
svm_C1_linear.svm_svm_print_accuracy_score(y_test)

In [ ]:
svm_C10_rbf = svm_model(C_value=10, kernel_value='rbf')
svm_C10_rbf.svm_train(X_train, y_train)
svm_C10_rbf.svm_predict(X_test)
svm_C10_rbf.svm_print_accuracy_score(y_test)
svm_C10_rbf.plot_confusion_matrix()

====== SVM Classifier with C = 10 kernel = rbf=========

In [ ]:
svm_C10_poly = svm_model(C_value=10, kernel_value='poly')
svm_C10_poly.svm_train(X_train, y_train)
svm_C10_poly.svm_predict(X_test)
svm_C10_poly.svm_print_accuracy_score(y_test)

In [24]:
svm_C100_rbf = svm_model(C_value=100, kernel_value='rbf')
svm_C100_rbf.svm_train(X_train, y_train)
svm_C100_rbf.svm_predict(X_test)
svm_C100_rbf.svm_print_accuracy_score(y_test)

====== SVM Classifier with C = 100 kernel = rbf=========

Calculating Accuracy of Predictions...
Accuracy score :  0.9046

In [25]:
svm_C100_poly = svm_model(C_value=100, kernel_value='poly')
svm_C100_poly.svm_train(X_train, y_train)
svm_C100_poly.svm_predict(X_test)
svm_C100_poly.svm_print_accuracy_score(y_test)

====== SVM Classifier with C = 100 kernel = poly=========

Calculating Accuracy of Predictions...
Accuracy score :  0.9